### ISSUE TITLE
l4d2_levelchanging: Does not work on "Competitive" modes.

### ISSUE THREAD

**Issue by SirPlease** [LuxLuma/Left-4-fix#1]
As the title says, this only appears to work on non versus/scavenge modes.
Not sure if you were aware.

**Comment by LuxLuma** [comment]
Ill look into it i never tested in those modes only coop and survival, as a note do you know if l4d uses trigger_changelevel entity for versus?

**Comment by LuxLuma** [comment]
Ok i have versus working but there is small problem i need to reset the scores because scores from other maps carry over, ill find an alt method but just updating you on progress.

**Comment by LuxLuma** [comment]
Added versus support i tested versus and scavenge seems to function as it should this still needs longterm testing enjoy.
