### ISSUE TITLE
AskPluginLoad Callback issue

### ISSUE THREAD

**Issue by markgs** [LuxLuma/Left-4-fix#2]
Hi,
What issue is this? Could it be Sourcemod version issue?

L 12/07/2019 - 21:51:17: [SM]   [1] Line 43, D:\Github\Left-4-fix\left 4 fix\l4d2_levelchanging\addons\sourcemod\scripting\l4d2_changelevel.sp::AskPluginLoad2
L 12/07/2019 - 21:51:17: [SM] Failed to load plugin "l4d2_changelevel.smx": unexpected error 23 in AskPluginLoad callback.

**Comment by LuxLuma** [comment]
Hello, I need abit more info.

1. What sourcemod version you running?
2. Are you running more than one instance of the plugin e.g. same plugin twice under 2 different names?
3. What version of the plugin are you running?
