### ISSUE TITLE
witch_prevent_target_loss.smx tries to patch twice the same adress if you you unload and then load this plugin for confogl

### ISSUE THREAD

**Issue by nikita1824** [LuxLuma/Left-4-fix#3]
error log:
L 03/28/2020 - 03:01:09: SourceMod error session started
L 03/28/2020 - 03:01:09: Info (map "c4m2_sugarmill_a") (file "errors_20200328.log")
L 03/28/2020 - 03:01:09: [witch_prevent_target_loss.smx] Incorrect offset for 'WitchAttack::OnMoveToFailure_1'.
L 03/28/2020 - 03:01:12: Error log file session closed.

**Comment by LuxLuma** [comment]
Are you by anychance using linux?

**Comment by nikita1824** [comment]
Yes, i use linux.

**Comment by LuxLuma** [comment]
This should solve the issue thanks.
